# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ColorView2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AWSCore', '~> 2.6.13'
  # Pods for ColorView2

end
